name: Pull Request
description: Submit your code changes to be reviewed and merged
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this pull request!
  - type: textarea
    id: desription
    attributes:
      label: Description
      description: Tell us more about your pull request.
      placeholder: |
        #### **Description**

        #### **How Has This Been Tested?**

        #### **Additional context**
        Add any other context or screenshots about the pull request here.
      value: |
        #### **Description**

        #### **How Has This Been Tested?**

        #### **Additional context**
        Add any other context or screenshots about the pull request here.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Check your PR vs the checklist
      options:
        - label: I have read, understood and followed our [Contributing Guide](https://github.com/pyhoneybot/honeybot/blob/master/CONTRIBUTING.md)
          required: true
        - label: My code follows the code style of this project
        - label: I have updated the documentation accordingly
        - label: I added my country flag to the README.md
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pyhoneybot/honeybot/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
