name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: Tell us more about the your suggested feature.
      placeholder: |
        #### **Is your feature request related to a problem?**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        #### **Describe the solution**
        A clear and concise description of what you want to happen.

        #### **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        #### **Additional context**
        Add any other context or screenshots about the feature request here.

      value: |
        #### **Is your feature request related to a problem?**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        #### **Describe the solution**
        A clear and concise description of what you want to happen.

        #### **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        #### **Additional context**
        Add any other context or screenshots about the feature request here.

    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pyhoneybot/honeybot/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
